"""initial schema

Revision ID: 3cd5ba85da9c
Revises: 
Create Date: 2026-01-21 14:43:49.915840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cd5ba85da9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_identifier'), 'otps', ['identifier'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('email_otp', sa.String(length=255), nullable=True),
    sa.Column('phone_otp', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('linkedin', sa.String(length=512), nullable=True),
    sa.Column('twitter', sa.String(length=512), nullable=True),
    sa.Column('facebook', sa.String(length=512), nullable=True),
    sa.Column('whatsapp', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_profiles_slug')
    )
    op.create_index(op.f('ix_profiles_slug'), 'profiles', ['slug'], unique=True)
    op.create_index('ix_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_profile', sa.Boolean(), nullable=True),
    sa.Column('show_phone', sa.Boolean(), nullable=True),
    sa.Column('show_email', sa.Boolean(), nullable=True),
    sa.Column('card_template', sa.String(), nullable=True),
    sa.Column('default_share_type', sa.String(), nullable=True),
    sa.Column('watermark_enabled', sa.Boolean(), nullable=True),
    sa.Column('nfc_enabled', sa.Boolean(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('target_profile_id', sa.UUID(), nullable=False),
    sa.Column('saved_display_name', sa.String(length=255), nullable=True),
    sa.Column('saved_phone', sa.String(length=64), nullable=True),
    sa.Column('saved_email', sa.String(length=255), nullable=True),
    sa.Column('saved_company', sa.String(length=255), nullable=True),
    sa.Column('saved_job_title', sa.String(length=255), nullable=True),
    sa.Column('saved_whatsapp', sa.String(length=64), nullable=True),
    sa.Column('saved_website', sa.String(length=1024), nullable=True),
    sa.Column('saved_linkedin', sa.String(length=512), nullable=True),
    sa.Column('saved_facebook', sa.String(length=512), nullable=True),
    sa.Column('saved_twitter', sa.String(length=512), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_owner_profile', 'contacts', ['owner_id', 'target_profile_id'], unique=False)
    op.create_table('nfc_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('encoded_url', sa.String(length=1024), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index('ix_nfc_profile', 'nfc_links', ['profile_id'], unique=False)
    op.create_table('profile_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'profile_audits', ['action'], unique=False)
    op.create_index('ix_audit_profile', 'profile_audits', ['profile_id'], unique=False)
    op.create_table('profile_card_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('background_color', sa.String(length=50), nullable=True),
    sa.Column('text_color', sa.String(length=50), nullable=True),
    sa.Column('background_image', sa.String(length=1024), nullable=True),
    sa.Column('logo', sa.String(length=1024), nullable=True),
    sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_card_settings')
    op.drop_index('ix_audit_profile', table_name='profile_audits')
    op.drop_index('ix_audit_action', table_name='profile_audits')
    op.drop_table('profile_audits')
    op.drop_index('ix_nfc_profile', table_name='nfc_links')
    op.drop_table('nfc_links')
    op.drop_index('ix_contacts_owner_profile', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('user_settings')
    op.drop_index('ix_profiles_user_id', table_name='profiles')
    op.drop_index(op.f('ix_profiles_slug'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otps_identifier'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
