"""add contacts table

Revision ID: 4bca1e067023
Revises: d150f1bb13d1
Create Date: 2025-12-10 10:49:24.650555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bca1e067023'
down_revision: Union[str, None] = 'd150f1bb13d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('saved_company', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('saved_job_title', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('saved_whatsapp', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('saved_website', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('saved_linkedin', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'saved_linkedin')
    op.drop_column('contacts', 'saved_website')
    op.drop_column('contacts', 'saved_whatsapp')
    op.drop_column('contacts', 'saved_job_title')
    op.drop_column('contacts', 'saved_company')
    # ### end Alembic commands ###
