"""increase otp column length

Revision ID: 9778ff12e6a1
Revises: 5b8fbac0c04c
Create Date: 2026-01-09 12:26:59.912287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9778ff12e6a1'
down_revision: Union[str, None] = '5b8fbac0c04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'saved_whatsapp',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('contacts', 'saved_website',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('contacts', 'saved_linkedin',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.drop_index(op.f('ix_contacts_owner_created'), table_name='contacts')
    op.alter_column('nfc_links', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_nfc_links_profile_active'), table_name='nfc_links')
    op.drop_index(op.f('ix_otps_identifier_used'), table_name='otps')
    op.create_index('ix_audit_action', 'profile_audits', ['action'], unique=False)
    op.create_index('ix_audit_profile', 'profile_audits', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_profiles_user_created'), table_name='profiles')
    op.alter_column('users', 'email_otp',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'phone_otp',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_otp',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('users', 'email_otp',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.create_index(op.f('ix_profiles_user_created'), 'profiles', ['user_id', 'created_at'], unique=False)
    op.drop_index('ix_audit_profile', table_name='profile_audits')
    op.drop_index('ix_audit_action', table_name='profile_audits')
    op.create_index(op.f('ix_otps_identifier_used'), 'otps', ['identifier', 'used'], unique=False)
    op.create_index(op.f('ix_nfc_links_profile_active'), 'nfc_links', ['profile_id', 'active'], unique=False)
    op.alter_column('nfc_links', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_contacts_owner_created'), 'contacts', ['owner_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('contacts', 'saved_linkedin',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('contacts', 'saved_website',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('contacts', 'saved_whatsapp',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
